POST http://localhost:3001/establishments/employee
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvbWJvcm9tYm8xMjNAZ21haWwuY29tIiwiaWQiOiI2MDE3ZTY5NTJiYzkzYzE5ZjRkYzIwMzYiLCJraW5kIjoiRXN0YWJsaXNobWVudCIsInJvbGUiOlsiYWRtaW4iXSwiaWF0IjoxNjEzMjczNjkwfQ.yHLFwam0l-JIekTP9fQtk_-4F6ANSX7cPPLcFftPDsE

{
    "firstName":"Felyn`",
    "lastName":"Fontila",
    "contactNumber":"639123456789",
    "password":"Jemuelemperor1",
    "email":"felynganda@.com"
}