POST http://localhost:3001/users/register/
Content-Type: application/json

{
    "firstName":"Jemuel",
    "middleName":"Yu",
    "lastName": "Fontila",
    "password": "12345678910",
    "passwordConfirmation": "12345678",
    "province": "Laguna",
    "city": "Sta Rosa",
    "barangay": "Market Area",
    "contactNumber":"0949602251",
    "email": "jemuelfontila123@gmail.com"
}