POST http://localhost:3001/users/register/
Content-Type: application/json

{
    "firstName":"J",
    "lastName": "",
    "password": "123",
    "verificationCode": "77120",
    "contactNumber": "639196022579",
    "email": "jemu125125elfontil121251251255125125a@gmail.com"
}