POST http://localhost:3001/users/register/
Content-Type: application/json

{
    "firstName":"Jemuel",
    "middleName":"Yu",
    "lastName": "Fontila",
    "password": "12345678910",
    "province": "Laguna",
    "city": "Sta Rosa",
    "barangay": "Market Area",
    "contactNumber":"09196022579",
    "verificationCode":"510174",
    "email": "jemuelfontila14223525@gmail.com"
}